name = "small-livecd-iso"
description = ""
version = "0.0.2"
modules = []
groups = []

[[customizations.user]]
name = "installer"
password = "$6$fB7uOFLqWoGTzWqO$gA.WYyR2eg3YicBBV.3jO.uo74cSw1c6XJ.PbKhTNEecD2Nq/wxOQ6jGF6WYpDdEfpH8xvxhRH7ZI/mOWeV730"
home = "/home/installer/"
shell = "/usr/bin/bash"
groups = ["users", "wheel"]
